const express = require('express');
const router = express.Router();
const { protect, adminOnly, superAdminOnly } = require('../middleware/auth');
const ctrl = require('../controllers/adminController');
router.use(protect, adminOnly);
router.get('/stats', ctrl.getDashboardStats);
router.get('/users', ctrl.getUsers);
router.patch('/users/:id/role', ctrl.updateUserRole);
router.patch('/users/:id/toggle', ctrl.toggleUserActive);
router.patch('/users/:id/kyc', ctrl.verifyKyc);
router.get('/alerts', ctrl.getAlerts);
router.post('/alerts', ctrl.createAlert);
router.delete('/alerts/:id', ctrl.deleteAlert);
router.get('/schemes', ctrl.getSchemes);
router.post('/schemes', ctrl.createScheme);
router.get('/market-prices', ctrl.getMarketPrices);
router.post('/market-prices', ctrl.updateMarketPrice);
router.get('/reports', ctrl.getReports);
router.post('/reports/generate', ctrl.generateReport);
module.exports = router;
